---
- name: Update the message of the day
  hosts: all
  become: yes
  tasks:
    - name: Deploy the 'motd' template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
