---
- name: Create users
  hosts: all
  become: yes
  tasks:
    - name: Load users
      include_vars:
        file: users.yml
        name: users
    - name: Load passwords
      include_vars:
        file: passwords.yml
        name: passwords
    - name: Create web user accounts
      user:
        name: "{{ item.username }}"
        comment: "{{ item.comment }}"
        password: "{{ passwords[item.username]['password'] | password_hash('sha512') }}"
        update_password: always
        state: present
      loop: "{{ users.webusers }}"
      when: "'webservers' in group_names"
    - name: Create database user accounts
      user:
        name: "{{ item.username }}"
        comment: "{{ item.comment }}"
        password: "{{ passwords[item.username]['password'] | password_hash('sha512') }}"
        update_password: always
        state: present
      loop: "{{ users.dbusers }}"
      when: "'databases' in group_names"

