---
- name: Delete users
  hosts: all
  become: yes
  vars:
    users_file: users.yml
  tasks:
    - name: Load users
      include_vars:
        file: "{{ users_file }}"
        name: users
    - name: Delete users
      user:
        name: "{{ item.username }}"
        remove: yes
        force: yes
        state: absent
      loop: "{{ users.list }}"
