---
- name: Create a specific user on all web servers
  hosts: webservers
  become: yes
  vars:
    username: webuser
  tasks:
    - name: Create the '{{ username }}' account
      user:
        name: "{{ username }}"
        state: present
