---
- name: Load users
  include_vars:
    file: "{{ users_file }}"
    name: users
- name: Load passwords
  include_vars:
    file: "{{ passwords_file }}"
    name: passwords
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    password: "{{ passwords[item.username]['password'] | password_hash('sha512') }}"
    update_password: always
    state: present
  loop: "{{ users.list }}"
